version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/openfga/api/proto
    except:
      - buf.build/googleapis/googleapis
      - buf.build/envoyproxy/protoc-gen-validate
      - buf.build/grpc-ecosystem/grpc-gateway
plugins:
  - plugin: buf.build/grpc-ecosystem/openapiv2:v2.16.0
    out: docs/openapiv2
    opt:
      - openapi_naming_strategy=simple
      - allow_merge=true
